# 01 Data Cleaning and Preprocessing

## Project Context
This notebook prepares the Netflix customer churn dataset for downstream analysis and modeling.

## Objectives
- Load and inspect the raw dataset
- Check structure, data types, missing values, and duplicates
- Clean unnecessary fields
- Handle basic data quality issues
- Save a cleaned dataset for EDA and modeling

In [1]:
import pandas as pd
import numpy as np

## 1. Load the Dataset

In [2]:
data_path = "../data/raw/netflix_customer_churn.csv"
df_raw = pd.read_csv(data_path)

df_raw.head()

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action

## 2. Initial Data Inspection

In [3]:
print("Dataset shape:", df_raw.shape)
print("\nColumn names:")
print(df_raw.columns)

Dataset shape: (5000, 14)

Column names:
Index(['customer_id', 'age', 'gender', 'subscription_type', 'watch_hours',
       'last_login_days', 'region', 'device', 'monthly_fee', 'churned',
       'payment_method', 'number_of_profiles', 'avg_watch_time_per_day',
       'favorite_genre'],
      dtype='object')

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             5000 non-null   object
 1   age                     5000 non-null   int64
 2   gender                  5000 non-null   object
 3   subscription_type       5000 non-null   object
 4   watch_hours             5000 non-null   float64
 5   last_login_days         5000 non-null   int64
 6   region                  5000 non-null   object
 7   device                  5000 non-null   object
 8   monthly_fee             5000 non-null   float64
 9   churned                 5000 non-null   int64
 10  payment_method          5000 non-null   object
 11  number_of_profiles      5000 non-null   int64
 12  avg_watch_time_per_day  5000 non-null   float64
 13  favorite_genre          5000 non-null   object
dtypes: float64(3), int64(4), object(7)
memory usage: 547.0+ KB

In [5]:
df_raw.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,5000,5000,a9b75100-82a8-427a-a208-72f24052884a,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,5000.0,NaN,NaN,NaN,43.8474,15.501128,18.0,30.0,44.0,58.0,70.0
gender,5000,3,Female,1711,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subscription_type,5000,3,Premium,1693,NaN,NaN,NaN,NaN,NaN,NaN,NaN
watch_hours,5000.0,NaN,NaN,NaN,11.64945,12.014654,0.01,3.3375,8.0,16.03,110.4
last_login_days,5000.0,NaN,NaN,NaN,30.0898,17.536078,0.0,15.0,30.0,45.0,60.0
region,5000,6,South America,873,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device,5000,5,Tablet,1048,NaN,NaN,NaN,NaN,NaN,NaN,NaN
monthly_fee,5000.0,NaN,NaN,NaN,13.6834,3.692062,8.99,8.99,13.99,17.99,17.99
churned,5000.0,NaN,NaN,NaN,0.503,0.500041,0.0,0.0,1.0,1.0,1.0
payment_method,5000,5,Debit Card,1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_of_profiles,5000.0,NaN,NaN,NaN,3.0244,1.415841,1.0,2.0,3.0,4.0,5.0
avg_watch_time_per_day,5000.0,NaN,NaN,NaN,0.8748,2.619824,0.0,0.11,0.29,0.72,98.42
favorite_genre,5000,7,Drama,731,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. Check Missing Values and Duplicates

In [6]:
missing_values = df_raw.isnull().sum()
missing_values

customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [7]:
duplicate_rows = df_raw.duplicated().sum()
print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 0

## 4. Check Target Variable Distribution

In [8]:
target_distribution = df_raw["churned"].value_counts()
target_ratio = df_raw["churned"].value_counts(normalize=True)

print("Target counts:")
print(target_distribution)

print("\nTarget ratio:")
print(target_ratio)

Target counts:
churned
1    2515
0    2485
Name: count, dtype: int64

Target ratio:
churned
1    0.503
0    0.497
Name: proportion, dtype: float64

## 5. Create a Working Copy
We keep the original dataset unchanged and perform cleaning on a copied version.

In [9]:
df_clean = df_raw.copy()

## 6. Remove Non-Predictive Identifier
`customer_id` is a unique identifier and does not provide predictive value for analysis or modeling.

In [10]:
df_clean = df_clean.drop(columns=["customer_id"])
df_clean.head()

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action

## 7. Validate Data Quality
This step checks for:
- missing values
- invalid ranges
- basic logical consistency

In [11]:
print("Missing values after dropping customer_id:")
print(df_clean.isnull().sum())

Missing values after dropping customer_id:
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [12]:
print("Unique values for categorical columns:\n")

categorical_columns = df_clean.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"{column}: {df_clean[column].unique()}")

Unique values for categorical columns:

gender: ['Other' 'Female' 'Male']
subscription_type: ['Basic' 'Standard' 'Premium']
region: ['Africa' 'Europe' 'Asia' 'Oceania' 'South America' 'North America']
device: ['TV' 'Mobile' 'Laptop' 'Desktop' 'Tablet']
payment_method: ['Gift Card' 'Crypto' 'Debit Card' 'PayPal' 'Credit Card']
favorite_genre: ['Action' 'Sci-Fi' 'Drama' 'Horror' 'Romance' 'Comedy' 'Documentary']

## 8. Handle Potential Data Issues
The original project clipped `avg_watch_time_per_day` at 24 hours.
This is a reasonable rule because daily watch time cannot logically exceed 24 hours.

In [13]:
df_clean["avg_watch_time_per_day"] = df_clean["avg_watch_time_per_day"].clip(upper=24)

In [14]:
df_clean["avg_watch_time_per_day"].describe()

count    5000.000000
mean        0.844990
std         2.035096
min         0.000000
25%         0.110000
50%         0.290000
75%         0.720000
max        24.000000
Name: avg_watch_time_per_day, dtype: float64

## 9. Optional Missing Value Treatment
The original dataset does not contain missing values, but we include a safe step for reproducibility.
For categorical columns, mode imputation is applied only if missing values exist.

In [15]:
if df_clean.isnull().sum().sum() > 0:
    df_clean = df_clean.fillna(df_clean.mode().iloc[0])

print("Remaining missing values:", df_clean.isnull().sum().sum())

Remaining missing values: 0

## 10. Final Review of Cleaned Dataset

In [16]:
print("Cleaned dataset shape:", df_clean.shape)
df_clean.head()

Cleaned dataset shape: (5000, 13)

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action

In [17]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     5000 non-null   int64
 1   gender                  5000 non-null   object
 2   subscription_type       5000 non-null   object
 3   watch_hours             5000 non-null   float64
 4   last_login_days         5000 non-null   int64
 5   region                  5000 non-null   object
 6   device                  5000 non-null   object
 7   monthly_fee             5000 non-null   float64
 8   churned                 5000 non-null   int64
 9   payment_method          5000 non-null   object
 10  number_of_profiles      5000 non-null   int64
 11  avg_watch_time_per_day  5000 non-null   float64
 12  favorite_genre          5000 non-null   object
dtypes: float64(3), int64(4), object(6)
memory usage: 507.9+ KB

## 11. Save Cleaned Dataset
This cleaned dataset will be used in later notebooks for EDA, modeling, and business analysis.

In [18]:
output_path = "../data/processed/netflix_churn_cleaned.csv"
df_clean.to_csv(output_path, index=False)

print(f"Cleaned dataset saved to: {output_path}")

Cleaned dataset saved to: ../data/processed/netflix_churn_cleaned.csv

In [19]:
4

4